spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

services:
  amp-url: https://dummy
  amp-subscription-key: dummy-key
  api-cp-crime-schedulingandlisting-courtschedule:
    path: /dummy
  api-cp-refdata-courthearing-courthouses:
    path: /dummy
  users:
    authorization-header: test-token
    aes-encryption-secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    hmac-encryption-secret: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=
  oauth-token:
    url: https://login.microsoftonline.com
    path: /{tenant}/oauth2/{version}/token
    tenant-id: tenant
    version: v2.0
    client-id: client-id
    client-secret: client-secret
    scope: api://scope/.default
