name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * MON-FRI" # MON-FRI at 04:30 UTC
  pull_request:

jobs:
  security-kotlin-owasp-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v2.8.7
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      nvd_feed_version: "2"
      java_version: '25'
    secrets: inherit
