name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "10 5 * * MON-FRI" # MON-FRI at 05:10 UTC
  pull_request:

jobs:
  security-veracode-pipeline-scan:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v2.8.7
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
      java_version: '25'
    secrets: inherit
